#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# RERO ILS
# Copyright (C) 2019 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# COLORS for messages
NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

PROGRAM=`basename $0`

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

invert_warning_option() {
  if ${ENABLE_WARNINGS}
  then
    ENABLE_WARNINGS=false
  else
    ENABLE_WARNINGS=true
  fi
}

invenio index queue purge delete
# invenio index destroy --force --yes-i-know

info_msg "Override index init to load templates before mapping"
# eval ${PREFIX} invenio utils init --force
# eval ${PREFIX} invenio index init --force
eval ${PREFIX} invenio index queue init

eval ${PREFIX} invenio utils reindex -t org --yes-i-know --no-info

info_msg "- Libraries:"
eval ${PREFIX} invenio utils reindex -t lib --yes-i-know --no-info

info_msg "- Locations:"
eval ${PREFIX} invenio utils reindex -t loc --yes-i-know --no-info

info_msg "- Item types:"
eval ${PREFIX} invenio utils reindex -t itty --yes-i-know --no-info

info_msg "- Patron types:"
eval ${PREFIX} invenio utils reindex -t ptty --yes-i-know --no-info

info_msg "- Circulation policies:"
eval ${PREFIX} invenio utils reindex -t cipo --yes-i-know --no-info
eval ${PREFIX} invenio utils runindex --raise-on-error

# info_msg "- PERSONS:"
# eval ${PREFIX} invenio utils reindex -t pers --yes-i-know --no-info
# eval ${PREFIX} invenio utils runindex --skip-errors --with_stats

info_msg "- Holdings:"
eval ${PREFIX} invenio utils reindex -t hold --yes-i-know --no-info
eval ${PREFIX} invenio utils runindex --skip-errors --with_stats

info_msg "- Items:"
eval ${PREFIX} invenio utils reindex -t item --yes-i-know --no-info
eval ${PREFIX} invenio utils runindex --skip-errors --with_stats

# index documents
eval ${PREFIX} invenio utils reindex -t doc --yes-i-know --no-info
eval ${PREFIX} invenio utils runindex --skip-errors --with_stats

# # ACQUISITION
info_msg "Acquisition vendors:"
eval ${PREFIX} invenio utils reindex -t vndr --yes-i-know --no-info

# create library budgets
info_msg "Library budgets:"
eval ${PREFIX} invenio utils reindex -t budg --yes-i-know --no-info

# create acquisition accounts
info_msg "Acquisition accounts:"
eval ${PREFIX} invenio utils reindex -t acac --yes-i-know --no-info

eval ${PREFIX} invenio utils runindex --skip-errors --with_stats

date
success_msg "Perfect ${PROGRAM}! See you soon…"
exit 0
